CREATE TABLE Users
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL UNIQUE,
    password varchar(100) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    role varchar(30) NOT NULL
);

CREATE TABLE Product(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50) NOT NULL UNIQUE,
    img_name varchar(50),
    date timestamp with time zone NOT NULL,
    price int,
    category varchar(30) NOT NULL
);

ALTER TABLE Product
    ADD amount int CHECK (amount >= 0) DEFAULT 0;

CREATE TABLE Orders
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id int REFERENCES Users(id) ON DELETE CASCADE,
    order_num int NOT NULL UNIQUE,
    creation_time timestamp with time zone NOT NULL,
    total_sum int NOT NULL
);

CREATE TABLE Order_details(
        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        product_id int REFERENCES Product(id),
        order_id int REFERENCES Orders(id),
        quantity int,
        price int NOT NULL,
        total_sum int
);

CREATE TABLE Bucket(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id int REFERENCES Users (id) ON DELETE CASCADE UNIQUE
);

CREATE TABLE Bucket_Product(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bucket_id int REFERENCES Bucket(id) ON DELETE CASCADE,
    product_id int REFERENCES Product(id) ON DELETE CASCADE
/*    PRIMARY KEYbucket_id, product_id)*/
);

DROP TABLE bucket_product;
DROP TABLE bucket;
DROP TABLE order_details;
DROP TABLE product;
DROP TABLE Orders;
DROP TABLE Users;

INSERT INTO Users (id, email, name, password, role)
VALUES (1, 'admin@mail.ru', 'admin', '$2a$10$45XS11YmDmJ4qjlXNdlVuuApgNjm.S7QTlTLmC4GKeMCcyYIMB0zC', 'ADMIN');

INSERT INTO Product(title, img_name, date, price, amount, category) VALUES
        ('Концерт Scally Milano', 'scally.jpg', '2022-11-03 17:00', 500, 200 , 'CONCERT'),
        ('Концерт Scorpions', 'scorpions.jpg', '2022-11-05 18:00', 700, 3000, 'CONCERT'),
        ('Концерт Lovv66', 'lovv66.jpeg' , '2022-12-25 17:00', 1500, 1200, 'CONCERT'),
        ('Футбольный матч Зенит - Ростов', 'zenit-rostov.jpg' , '2022-12-20 19:00', 1500, 15000, 'SPORT'),
        ('Баскетбольный матч Зенит - Цска', 'zenit-cska.jpg' , '2022-11-15 18:00', 1500, 5000, 'SPORT');

INSERT INTO Product(title, img_name, date, price, amount, category) VALUES
         ('Опера щелкунчик', 'nutcracker.jpg', '2023-01-20 18:00', 1700, 3, 'THEATRE');

DELETE FROM Product WHERE title = 'Опера щелкунчик';
DELETE FROM Users WHERE id = 1;

SELECT * FROM Users;

DELETE FROM Product WHERE id >= 1;
DELETE FROM Users WHERE id >= 1;
DELETE FROM Bucket WHERE id >= 1;
SELECT * FROM Product;

SELECT u.name,  P.title from Users u
JOIN Bucket B on u.id = B.user_id
JOIN Bucket_Product BP on B.id = BP.bucket_id
JOIN Product P on P.id = BP.product_id;

ALTER SEQUENCE users_id_seq RESTART WITH 2;
ALTER SEQUENCE product_id_seq RESTART WITH 1;
ALTER SEQUENCE bucket_id_seq RESTART WITH 1;

SET timezone = 'Europe/Moscow';




